use_frameworks!
platform :ios, '8.0'

target 'ContactInvitationPicker' do
  
  # Pods for ContactInvitationPicker

  target 'ContactInvitationPickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
